services:
  docs:
    image: audio_transcript_local_docs
    container_name: audio_transcript_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./audio_transcript:/app/audio_transcript:z
    ports:
      - '9000:9000'
    command: /start-docs
